io:
  input_video: data/input/scene.mp4
  output_root: data/output_vod/scene_A
preprocess:
  gop: 12
  target_layers: 4
  depth_model: depth_anything_v2_vitl
  depth_checkpoint: ../Depth-Anything-V2/checkpoints/depth_anything_v2_vitl.pth
  depth_repo: ../Depth-Anything-V2
  depth_input_size: 518
  spatial_weight: 0.35
  depth_smooth_kernel: 7
  min_area_ratio: 0.004
  boundary_band_px: 5
  soft_alpha_sigma: 2.5
  soft_alpha_max: 0.95
  device: cuda
playback:
  fps: 30
  viewer_intrinsics:
    fx: 1100
    fy: 1100
    cx: 960
    cy: 540
  max_view_offset: 0.08
